#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
VNC_SERVER=${VNC_SERVER}
VNC_PORT_SLOT=${VNC_PORT_SLOT}
----------------------------------------------------------------------
"
