#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
VNC_SERVER=${VNC_SERVER}
VNC_PORT=${VNC_PORT}
----------------------------------------------------------------------
"
