#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

vnc_port=$(( 5900 + VNC_PORT_SLOT ))
novnc_port=$(( 6080 + VNC_PORT_SLOT ))

exec s6-setuidgid hotio "${APP_DIR}/utils/novnc_proxy" --vnc "${VNC_SERVER}:${vnc_port}" --listen "0.0.0.0:${novnc_port}"
